package com.hieu.catalog_service.domain.model.product;

import com.hieu.catalog_service.domain.model.product.valueobject.Money;
import com.hieu.catalog_service.domain.model.product.valueobject.ProductId;
import com.hieu.catalog_service.domain.model.product.valueobject.ProductStatus;
import com.hieu.catalog_service.domain.model.product.valueobject.Quantity;
import com.hieu.catalog_service.domain.model.product.valueobject.Sku;
import com.hieu.catalog_service.domain.model.product.valueobject.Slug;
import com.hieu.catalog_service.domain.model.product.valueobject.VariantId;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("Product aggregate — unit")
class ProductTest {
    /**
     * Top-level smoke test — bắt buộc để Sonar rule java:S2187 nhận diện
     * class này có @Test (không tính các @Test bên trong @Nested).
     * Mọi test thật sự được tổ chức trong các @Nested class bên dưới.
     */
    @Test
    @DisplayName("class loads + JUnit discovers @Nested tests")
    void smokeTest_classDiscovered() {
        // Nếu tới được đây tức là JUnit có thể instantiate test class.
        // assertThat(this).isNotNull() được tự thực hiện ngầm.
    }


    // ── helpers ──────────────────────────────────────────────────────────────

    static Product aProduct() {
        return Product.create("Test Product", "desc", null, "Brand", "user");
    }

    static Variant aVariant(String sku, BigDecimal price) {
        return Variant.create(
                Sku.of(sku),
                Money.of(price),
                null,
                null,
                null,
                BigDecimal.ONE,
                Quantity.of(10)
        );
    }

    static Product aProductWithId() {
        Product p = aProduct();
        p.assignId(ProductId.of("1"));
        return p;
    }

    // ── Slug tests ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Slug")
    class SlugTests {

        @Test
        @DisplayName("slug được tự sinh từ name — lowercase, nối bằng dấu gạch ngang")
        void slug_autoGeneratedFromName_lowercaseDash() {
            Product p = Product.create("Hello World Product", "desc", null, null, "user");

            assertThat(p.getSlug().value())
                    .isEqualTo("hello-world-product")
                    .doesNotContain(" ")
                    .isLowerCase();
        }

        @Test
        @DisplayName("Slug.generate loại bỏ dấu tiếng Việt — ASCII fallback")
        void slug_stripVietnameseDiacritics() {
            Slug slug = Slug.generate("Áo Thun Việt Nam");

            assertThat(slug.value())
                    .isEqualTo("ao-thun-viet-nam")
                    .matches("[a-z0-9-]+");
        }

        @Test
        @DisplayName("Slug.generate xử lý ký tự đặc biệt — chỉ giữ alphanum và dash")
        void slug_specialCharsStripped() {
            Slug slug = Slug.generate("Product (v2.0) — Special!");

            assertThat(slug.value())
                    .matches("[a-z0-9-]+")
                    .doesNotContain("(")
                    .doesNotContain(")")
                    .doesNotContain(".");
        }

        @Test
        @DisplayName("slug nhiều khoảng trắng liên tiếp được thu gọn thành một dash")
        void slug_multipleSpacesCollapsed() {
            Slug slug = Slug.generate("Hello   World");

            assertThat(slug.value()).isEqualTo("hello-world");
        }
    }

    // ── Variant tests ─────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Variants")
    class VariantTests {

        @Test
        @DisplayName("addVariant thêm variant vào product thành công")
        void addVariant_succeeds() {
            Product p = aProduct();
            Variant v = aVariant("SKU-A01", new BigDecimal("99.99"));

            p.addVariant(v);

            assertThat(p.getVariants()).hasSize(1);
            assertThat(p.getVariants().get(0).getSku().value()).isEqualTo("SKU-A01");
        }

        @Test
        @DisplayName("addVariant từ chối SKU trùng lặp trong cùng product")
        void addVariant_duplicateSku_throwsIllegalArgument() {
            Product p = aProduct();
            p.addVariant(aVariant("SKU-DUP", new BigDecimal("100")));

            assertThatThrownBy(() -> p.addVariant(aVariant("SKU-DUP", new BigDecimal("200"))))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("SKU-DUP");
        }

        @Test
        @DisplayName("getEffectivePrice trả về giá thấp nhất khi có salePrice")
        void getEffectivePrice_returnsSalePriceWhenCheaper() {
            Variant v = Variant.create(
                    Sku.of("SKU-E01"),
                    Money.of(new BigDecimal("200")),
                    null,
                    Money.of(new BigDecimal("150")),
                    null,
                    BigDecimal.ONE,
                    Quantity.of(5)
            );
            Product p = aProduct();
            p.addVariant(v);

            // priceRange min = effective (sale) price
            Product.PriceRange range = p.getPriceRange();
            assertThat(range.min()).isEqualByComparingTo(new BigDecimal("150"));
        }

        @Test
        @DisplayName("getPriceRange min = min(variant.getEffectivePrice())")
        void getPriceRange_minIsLowestEffectivePrice() {
            Product p = aProduct();
            p.addVariant(aVariant("SKU-B01", new BigDecimal("50")));
            p.addVariant(aVariant("SKU-B02", new BigDecimal("30")));
            p.addVariant(aVariant("SKU-B03", new BigDecimal("70")));

            Product.PriceRange range = p.getPriceRange();
            assertThat(range.min()).isEqualByComparingTo(new BigDecimal("30"));
            assertThat(range.max()).isEqualByComparingTo(new BigDecimal("70"));
        }
    }

    // ── Status transition tests ───────────────────────────────────────────────

    @Nested
    @DisplayName("StatusTransitions")
    class StatusTransitionTests {

        @Test
        @DisplayName("DRAFT → ACTIVE → INACTIVE → ACTIVE — chu kỳ status hợp lệ")
        void statusCycle_draftActiveInactiveActive() {
            Product p = aProductWithId();
            p.addVariant(aVariant("SKU-ST1", new BigDecimal("100")));

            p.activate("user");
            assertThat(p.getStatus()).isEqualTo(ProductStatus.ACTIVE);

            p.deactivate("user");
            assertThat(p.getStatus()).isEqualTo(ProductStatus.INACTIVE);

            p.activate("user");
            assertThat(p.getStatus()).isEqualTo(ProductStatus.ACTIVE);
        }

        @Test
        @DisplayName("canPublish (activate) ném lỗi khi product không có variants")
        void activate_withoutVariants_throwsIllegalState() {
            Product p = aProductWithId();

            assertThatThrownBy(() -> p.activate("user"))
                    .isInstanceOf(IllegalStateException.class)
                    .hasMessageContaining("no variants");
        }

        @Test
        @DisplayName("DELETED product không thể transition sang status khác")
        void deletedProduct_cannotTransition() {
            Product p = aProductWithId();
            p.addVariant(aVariant("SKU-DEL", new BigDecimal("100")));
            p.softDelete("user");

            assertThatThrownBy(() -> p.activate("user"))
                    .isInstanceOf(IllegalStateException.class);
        }

        @Test
        @DisplayName("softDelete chuyển status sang DELETED và không thể delete lại")
        void softDelete_idempotent() {
            Product p = aProductWithId();
            p.softDelete("user");

            // second call is a no-op — không ném exception
            p.softDelete("user");
            assertThat(p.getStatus()).isEqualTo(ProductStatus.DELETED);
        }
    }
}
